name: Build on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        sudo apt-get -y install meson libwireplumber-0.5
    - name: build
      run: |
        meson setup build
        ninja -C build
